const actionTypes = {
  LOAD_INITIAL_CONTACTS: 'LOAD_INITIAL_CONTACTS',
  EDIT_CONTACT: 'EDIT_CONTACT',
  ADD_CONTACT: 'ADD_CONTACT',
  DELETE_CONTACT: 'DELETE_CONTACT',
  SEARCH_CONTACT: 'SEARCH_CONTACT',
};

export default actionTypes;
